version: '3.1'
services:
  php-go-server:
    build: webserver
    container_name: "php-go-round"
    ports:
        - "50000:8080"
    volumes:
        - ./src:/app/src
        - ./public:/app/public
        - ./webserver/php.ini:/usr/local/etc/php/php.ini
        - ./logs:/var/log
