name: PHPStan

on:
    push:
      branches:
        - '**'

jobs:
    phpstan-check:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: List files
        run: ls -la

      - name: Run PHPStan
        run: docker/phpstan.sh

